/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "GPIO.h"
#include "USART.h"

short buffer[100];
FIFO_Buffer UART_buffer = {96,0,(unsigned short*)buffer,(unsigned short*)buffer,(unsigned short*)buffer};

void USART_IRQ_handler()
{
	if(USART1->SR & USART_RXNE)
	{
		if(UART_buffer.count == UART_buffer.length)
		{
			USART1->CR1 &= ~USART_IRQ_RXE;
		}

		else if (USART1->CR1 & USART_IRQ_RXE) MCAL_USART_RECV(USART1, &UART_buffer, USART_SERV_IRQ);

	}

	if(USART1->SR & USART_TXE)
	{
		if(UART_buffer.count == 0)
		{
			USART1->CR1 &= ~USART_IRQ_TXE;
		}

		else if (USART1->CR1 & USART_IRQ_TXE) MCAL_USART_SEND(USART1, &UART_buffer, USART_SERV_IRQ);
	}
}

int main(void)
{
	USART_CNFQ_t USART_config;

	USART_config.BAUD_RATE = USART_115200;
	USART_config.FLOW = USART_FLOW_NONE;
	USART_config.IRQ = USART_IRQ_TXE_RXE;
	USART_config.LENGTH = USART_LENGTH_8;
	USART_config.MODE = USART_MODE_TX_RX;
	USART_config.PARITY = USART_PARITY_NONE;
	USART_config.STOP = USART_STOP_10;
	USART_config.P_IRQ_CallBack = USART_IRQ_handler;

	MCAL_USART_Init(USART1, &USART_config);

	while (1)
    {
		MCAL_USART_SEND(USART1, &UART_buffer, USART_SERV_POLL);
    }
}
