/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "GPIO.h"
#include "LCD.h"
#include "EXTI.h"

int IRQ_Flag = 1;

void CLK_init ()
{
	//enable clock for GPIOA & GPIOB
	RCC_CLOCK_GPIOA_EN ;
	RCC_CLOCK_GPIOB_EN ;
	RCC_CLOCK_AFIO_EN;

}

void delay_loop(int x)
{
	int i,j;
	for(i=0;i<255;i++)
	{
		for(j=0;j<x;j++);
	}
}

void EXTI9_callback(void)
{
	IRQ_Flag=1;
	LCD_send_string("IRQ9 is pinned & being serviced");
	delay_loop(1000);


}

int main(void)
{
	CLK_init();

	LCD_init();
	LCD_send_string("LCD");
	LCD_send_command(LCD_BEGIN_AT_SECOND_ROW);
	LCD_send_string("initialized");
	delay_loop(1000);
	LCD_send_command(LCD_CLEAR_SCREEN);

	EXTI_CNFQ_t EXTI_PB9;
	EXTI_PB9.EXTI_PIN = EXTI9PB9;
	EXTI_PB9.TRIG_MODE = EXTI_RISING;
	EXTI_PB9.STATE = EXTI_EN;
	EXTI_PB9.P_IRQ_CallBack = EXTI9_callback;
	MCAL_EXTI_Init(&EXTI_PB9);

	while (1)
    {
		if (IRQ_Flag)
		{
			LCD_send_command(LCD_CLEAR_SCREEN);
			IRQ_Flag = 0;
		}
		delay_loop(50);
    }
}
