/*
 * LCD_Keypad_atmega32.c
 *
 * Created: 7/7/2022 1:17:05 PM
 * Author : momen
 */ 
#define	F_CPU 8000000UL
#include <util/delay.h>
#include "Include/GPIO.h"
#include "Include/I2C.h"

int main(void)
{
	MCAL_I2C_Init(MODE_MASTER, 100000, 0);
	
	MCAL_GPIO_Init(GPIOA,GPIO_PIN_0,MODE_OUTPUT_PP);
	MCAL_GPIO_Init(GPIOA,GPIO_PIN_1,MODE_OUTPUT_PP);
	MCAL_GPIO_Init(GPIOA,GPIO_PIN_2,MODE_OUTPUT_PP);
	MCAL_GPIO_Init(GPIOA,GPIO_PIN_3,MODE_OUTPUT_PP);
	MCAL_GPIO_Init(GPIOA,GPIO_PIN_4,MODE_OUTPUT_PP);
	MCAL_GPIO_Init(GPIOA,GPIO_PIN_5,MODE_OUTPUT_PP);
	MCAL_GPIO_Init(GPIOA,GPIO_PIN_6,MODE_OUTPUT_PP);
	MCAL_GPIO_Init(GPIOA,GPIO_PIN_7,MODE_OUTPUT_PP);	
	
	uint8_t C=0;
	while (1) 
    {		
		MCAL_I2C_Start();
		while (MCAL_I2C_Write(MODE_MASTER, 0XF0+1) != MASTER_SLA_R_ACK_TRANSMITT);
		MCAL_I2C_Read(MODE_MASTER, &C);
		MCAL_I2C_Stop();
		
		MCAL_GPIO_WRITE_PORT(GPIOA, C);
		_delay_ms(100);		
	}
}
