/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "GPIO.h"

void CLK_init ()
{
	//enable clock for GPIOA & GPIOB
	RCC_CLOCK_GPIOA_EN() ;
	RCC_CLOCK_GPIOB_EN() ;

}

void GPIO_init()
{
	GPIO_PIN_CNFQ_t Pinconfig ;

	//PA.1 & PA.13 as floating input
	Pinconfig.PIN_NUMBER = GPIO_PIN_0;
	Pinconfig.MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA , &Pinconfig);

	Pinconfig.PIN_NUMBER = GPIO_PIN_13;
	Pinconfig.MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA , &Pinconfig);


	//PB.1 & PB.13 as push-pull output
	Pinconfig.PIN_NUMBER = GPIO_PIN_1;
	Pinconfig.MODE = GPIO_MODE_OUTPUT_PP;
	Pinconfig.SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB , &Pinconfig);

	Pinconfig.PIN_NUMBER = GPIO_PIN_13;
	Pinconfig.MODE = GPIO_MODE_OUTPUT_PP;
	Pinconfig.SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB , &Pinconfig);

}

void delay_loop(int x)
{
	int i;
	for(i=0;i<x;i++);
}

int main(void)
{
	CLK_init();
	GPIO_init();

	//flag required for button1 non-blocking operation
	int F_A0=0;
	while(1)
	{
		//to make button1 work in single press way without blocking the other button
		if(MCAL_GPIO_READ_PIN(GPIOA, GPIO_PIN_1))
		{
			//if button1 is depressed then zero the flag
			F_A0 = 0;
		}
		else
		{
			//if button1 is pressed then check the flag if set then it's not the first time
			if(F_A0==0)
			{
				//if button1 is pressed for the first time then set the flag for next time and toggle
				F_A0 = 1;
				MCAL_GPIO_TOGGLE_PIN(GPIOB, GPIO_PIN_1);
			}

		}

		//to make button2 work in multi-press way
		if(MCAL_GPIO_READ_PIN(GPIOA, GPIO_PIN_13))
		{
			MCAL_GPIO_TOGGLE_PIN(GPIOB, GPIO_PIN_13);
		}

		delay_loop(5000);
	}
}
